# opensearch-values.yaml

clusterName: "opensearch-cluster"
nodeGroup: "master"

roles:
  - master
  - ingest
  - data
  - remote_cluster_client

replicas: 1

config:
  opensearch.yml:
    plugins:
      security:
        disabled: true

persistence:
  enabled: false  # Enable this in production with appropriate storage class

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: NodePort  # Change to LoadBalancer or NodePort if external access is needed
