# opensearch-values.yaml

clusterName: "opensearch-cluster"
nodeGroup: "master"

roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "true"

replicas: 1

esConfig:
  opensearch.yml: |
    plugins.security.disabled: true  # Disable security features for simplicity; not recommended for production

persistence:
  enabled: false  # Enable this in production with appropriate storage class

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: NodePort  # Change to LoadBalancer or NodePort if external access is needed
